admin:
  existingSecret: keycloak-secrets
  secretKeys:
    username: username
    password: password

db:
  existingSecret: postgresql-secrets
  secretKeys:
    username: POSTGRES_USER
    password: POSTGRES_PASSWORD
    database: POSTGRES_DB

postgresql:
  auth:
    existingSecret: postgresql-secrets
    secretKeys:
      username: POSTGRES_USER
      password: POSTGRES_PASSWORD
      database: POSTGRES_DB
  primary:
    persistence:
      enabled: false
    
production: false
proxyAddressForwarding: true

global:
  security:
    allowInsecure: true

test:
  enabled: false

ingress:
  enabled: false

image:
  registry: docker.io
  repository: bitnami/keycloak
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

service:
  port: 8080
