spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://postgres:5432/forms-ai
    username: postgres
    password: postgres-secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_URL:http://localhost:9001}/realms/forms-ai
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8083

keycloak:
  realm: forms-ai
  server-url: ${KEYCLOAK_URL:http://localhost:9001}
  clientId: user-service
  client-secret: user-service-secret

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: unrestricted

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

jwt:
  auth:
    converter:
      resource-id: angular-frontend
      principle-attribute: preferred_username
