spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.team-kruschefan-project.svc.cluster.local:8080/realms/forms-ai
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://keycloak.team-kruschefan-project.svc.cluster.local:8080
