spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_URL:keycloak.team-kruschefan-project.svc.cluster.local}/realms/forms-ai
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://${KEYCLOAK_URL:keycloak.team-kruschefan-project.svc.cluster.local}
