spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.team-kruschefan.local/realms/forms-ai
          jwk-set-uri: http://keycloak.team-kruschefan-project.svc.cluster.local:8080/realms/forms-ai/protocol/openid-connect/certs

keycloak:
  server-url: http://keycloak.team-kruschefan-project.svc.cluster.local:8080
