apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-schema-loader
spec:
  template:
    spec:
      restartPolicy: Never
      backoffLimit: 0
      containers:
        - name: schema-loader
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.command }}
          args: {{ .Values.args }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
