alertmanager:
  enabled: false

server:
  service:
    type: ClusterIP
    port: 9090
  ingress:
    enabled: false

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheus-node-exporter:
  enabled: true
