global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.com'

route:
  receiver: 'default'

receivers:
  - name: 'default'
    email_configs:
      - to: 'jay0816@outlook.com'
        send_resolved: true
