version: '3.8'

services:

  # Angular for frontend
  angular-client:
    build:
      context: ./client
    ports:
      - "4200:80"

  # Langchain GenAI service
  langchain-app:
    build:
      context: ./GenAI
    ports:
      - "8000:8000"
    working_dir: /GenAI
    volumes:
      - ./GenAI:/GenAI
      - ./GenAI/llm:/models
    environment:
      - PYTHONUNBUFFERED=1
      - HUGGINGFACEHUB_API_KEY=${HUGGINGFACEHUB_API_KEY}
      - MONGO_URI=${MONGO_URI}

  # Postgres for keycloak
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: forms-ai
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql:ro
    networks:
      - shared-net

  # Keycloak, user auth service
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    volumes:
      - ./keycloak/create-realm.sh:/opt/keycloak/create-realm.sh
    entrypoint: ["/opt/keycloak/create-realm.sh"]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: forms-ai
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: localhost
    ports:
      - "9001:8080"
    depends_on:
      - postgres
    networks:
      - shared-net  
  
  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Alertmanager for alert sending
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    ports:
      - "9093:9093"

  # Grafana for app data visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEYCLOAK_REALM=forms-ai
    depends_on:
      - postgres
      - keycloak
    networks:
      - shared-net

  form-service:
    build:
      context: .
      dockerfile: form-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  template-service:
    build:
      context: .
      dockerfile: template-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - user-service
      - form-service
      - template-service
      - langchain-app

volumes:
  postgres-data:
  grafana-data:

networks:
  shared-net:
