image:
  repository: ghcr.io/YOUR_USERNAME/mongo-schema-loader  # TODO: push image to registry 
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: MONGO_URI
    valueFromSecret:
      name: project-secrets
      key: mongo_uri

command: ["python"]
args: ["schema_loader.py"]
