image:
  repository: ghcr.io/cjzbeastmode/mongo-schema-loader:latest
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: MONGO_URI
    valueFromSecret:
      name: project-secrets
      key: mongo_uri

command: ["python"]
args: ["schema_loader.py"]
