image:
  repository: ghcr.io/aet-devops25/mongo-schema-loader  # TODO: push image to registry 
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: MONGO_URI
    value: mongodb://mongo:27017

command: ["python"]
args: ["schema_loader.py"]
