replicaCount: 1

image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

postgresql:
  existingSecret: postgresql-secrets
  secretKeys:
    username: POSTGRES_USER
    password: POSTGRES_PASSWORD
    database: POSTGRES_DB

serviceAccount:
  create: true
  name: "postgres"

# TODO: change ingress config
ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80