keycloak:
  image:
    registry: docker.io
    repository: bitnami/keycloak
    tag: latest
    pullPolicy: IfNotPresent

  production: false
  proxyAddressForwarding: true

  auth:
    adminUser: admin
    existingSecret: project-secrets
    passwordSecretKey: keycloak_admin_password

  service:
    type: ClusterIP
    ports:
      http: 8080

  database:
    vendor: postgresql
    externalDatabase:
      host: postgres
      port: 5432
      user: keycloak
      database: keycloak
      existingSecret: project-secrets
      existingSecretPasswordKey: postgres_password

  global:
    security:
      allowInsecureImages: true

  test:
    enabled: false

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

image:
  registry: docker.io
  repository: bitnami/keycloak
  tag: latest
  pullPolicy: IfNotPresent