auth:
  adminUser: admin
  adminPassword: admin

postgresql:
  auth:
    username: bn_keycloak
    password: password
    database: keycloak
    
production: false
proxyAddressForwarding: true

global:
  security:
    allowInsecure: true

test:
  enabled: false

ingress:
  enabled: false

image:
  registry: docker.io
  repository: bitnami/keycloak
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

service:
  port: 8080

postgresql:
  primary:
    persistence:
      enabled: false