replicaCount: 1

image:
  repository: mongo-express
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

env:
  - name: ME_CONFIG_MONGODB_SERVER
    value: mongodb
  - name: ME_CONFIG_MONGODB_ADMINUSERNAME
    value: "root"
  - name: ME_CONFIG_MONGODB_ADMINPASSWORD
    value: "example"
  - name: ME_CONFIG_BASICAUTH_USERNAME
    valueFromSecret:
      name: project-secrets
      key: mongo_express_user
  - name: ME_CONFIG_BASICAUTH_PASSWORD
    valueFromSecret:
      name: project-secrets
      key: mongo_express_password

serviceAccount:
  create: true
  name: ""

# TODO: change ingress config
ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80