replicaCount: 1

image:
  repository: mongo-express
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

env:
  - name: ME_CONFIG_MONGODB_SERVER
    value: mongodb
  - name: ME_CONFIG_MONGODB_ADMINUSERNAME
    valueFromSecret:
      name: project-secrets
      key: mongo_root_username
  - name: ME_CONFIG_MONGODB_ADMINPASSWORD
    valueFromSecret:
      name: project-secrets
      key: mongo_root_password
  - name: ME_CONFIG_BASICAUTH_USERNAME
    valueFromSecret:
      name: project-secrets
      key: mongo_express_user
  - name: ME_CONFIG_BASICAUTH_PASSWORD
    valueFromSecret:
      name: project-secrets
      key: mongo_express_password
