apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: team-kruschefan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
        - name: keycloak-init
          image: quay.io/keycloak/keycloak:24.0.1
          command:
            - sh
            - -c
            - |
              cp /opt/keycloak/init/init-keycloak.sh /tmp/init.sh && \
              chmod +x /tmp/init.sh && \
              sh /tmp/init.sh
          env:
            - name: KEYCLOAK_ADMIN
              value: keycloak
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: keycloak-secret
            - name: KEYCLOAK_SERVICE_HOST
              value: localhost
            - name: KEYCLOAK_SERVICE_PORT
              value: "8080"
          volumeMounts:
            - name: keycloak-init-script
              mountPath: /opt/keycloak/init/init-keycloak.sh
              subPath: init-keycloak.sh
              readOnly: true


      containers:
        - name: keycloak
          image: "quay.io/keycloak/keycloak:24.0.1"
          command:
            - "/opt/keycloak/bin/kc.sh"
          args:
            - "start-dev"
            - "--hostname-strict=false"
            - "--hostname-strict-https=false"
          ports:
            - containerPort: 8080
          env:
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL_HOST
              value: "postgres"
            - name: KC_DB_URL_DATABASE
              value: "forms-ai"
            - name: KC_DB_USERNAME
              value: "postgres"
            - name: KC_DB_PASSWORD
              value: "postgres-pw"
            - name: KEYCLOAK_ADMIN
              value: "keycloak"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "keycloak-secret"
            - name: KC_HOSTNAME
              value: "localhost"

      volumes:
        - name: keycloak-init-script
          configMap:
            name: keycloak-init-script
