apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "keycloak.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "keycloak.name" . }}
    spec:
      containers:
        - name: keycloak
          image: "quay.io/keycloak/keycloak:24.0.1"
          command: ["sh", "/opt/keycloak/create-realm.sh"]
          ports:
            - containerPort: 8080
          env:
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL_HOST
              value: "postgres"
            - name: KC_DB_URL_DATABASE
              value: "keycloak"
            - name: KC_DB_USERNAME
              value: "{{ .Values.db.username }}"
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: password
            - name: KEYCLOAK_ADMIN
              value: "{{ .Values.admin.username }}"
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: adminPassword
            - name: KC_HOSTNAME
              value: "localhost"
          volumeMounts:
            - name: keycloak-init
              mountPath: /opt/keycloak/create-realm.sh
              subPath: create-realm.sh
      volumes:
        - name: keycloak-init
          configMap:
            name: keycloak-init-script