apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: keycloak
spec:
  type: ClusterIP  # Internal cluster service
  ports:
    - name: http
      port: 8080  # Matches your service.port in values.yaml
      targetPort: 8080  # Default Keycloak HTTP port
      protocol: TCP
  selector:
    app: keycloak  # Matches your pod's label