replicaCount: 1

image:
  repository: ghcr.io/cjzbeastmode/user-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP 
  port: 8083

env:
  - name: SPRING_PROFILES_ACTIVE
    value: k8s

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

imagePullSecrets:
  - name: ghcr-cred
