apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: team-kruschefan-project
data:
  alert.rules.yml: |
    groups:
      - name: example
        rules:
          - alert: AlwaysFiring
            expr: vector(1)
            for: 10s
            labels:
              severity: test
            annotations:
              summary: "This alert always fires"
