apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: team-kruschefan-project
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
    alertmanagers:
      - static_configs:
          - targets:
              - alertmanager:9093
    
    rule_files:
      - /opt/bitnami/prometheus/conf/alert.rules.yml

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: 'langchain-app'
        static_configs:
          - targets: ['langchain-app.team-kruschefan-project.svc.cluster.local:8000']

      - job_name: 'api-gateway'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['api-gateway.team-kruschefan-project.svc.cluster.local:8080']

      - job_name: 'form-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['form-service.team-kruschefan-project.svc.cluster.local:8081']

      - job_name: 'template-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['template-service.team-kruschefan-project.svc.cluster.local:8082']

      - job_name: 'user-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['user-service.team-kruschefan-project.svc.cluster.local:8083']
