apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app: prometheus
