- name: Install dependencies
  ansible.builtin.dnf:
    name:
      - curl
    state: present

- name: Download kubectl binary
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/v1.30.1/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Ensure kubectl is executable
  ansible.builtin.file:
    path: /usr/local/bin/kubectl
    mode: '0755'
