image:
  repository: mongo
  tag: 6.0.13
  pullPolicy: IfNotPresent

auth:
  enabled: true
  existingSecret: mongodb-secrets
  usePasswordFiles: true

service:
  type: ClusterIP
  port: 27017

persistence:
  enabled: true
  storageClass: local-path
  size: 1Gi
  accessModes:
    - ReadWriteOnce

resources:
  limits:
    memory: 2Gi
  requests:
    memory: 1Gi

serviceAccount:
  create: true
  name: "mongodb"
  automount: true

# TODO: change ingress
ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
