replicaCount: 1

image:
  repository: ghcr.io/cjzbeastmode/user-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP 
  port: 8083

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: KEYCLOAK_REALM
    value: master
  - name: KEYCLOAK_CLIENT_ID
    value: admin-cli
  - name: KEYCLOAK_USERNAME
    value: admin
  - name: KEYCLOAK_PASSWORD
    value: admin
  - name: KEYCLOAK_URL
    value: http://keycloak:9001


serviceAccount:
  create: true
  name: ""

# TODO: change ingress config
ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

imagePullSecrets:
  - name: ghcr-cred
