replicaCount: 1

image:
  repository: ghcr.io/YOUR_USERNAME/template-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: MONGO_URI
    valueFromSecret:
      name: project-secrets
      key: mongo_uri
