replicaCount: 1

image:
  repository: ghcr.io/aet-devops25/template-service # TODO: push image to registry
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: MONGO_URI
    valueFromSecret:
      name: project-secrets
      key: mongo_uri

serviceAccount:
  create: true
  name: ""

# TODO: change ingress config
ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80