apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: team-kruschefan-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: "quay.io/keycloak/keycloak:24.0.1"
          volumeMounts:
            - name: keycloak-init-script
              mountPath: /opt/keycloak/init/init-keycloak.sh
              subPath: init-keycloak.sh
              readOnly: true

          command:
            - sh
            - -c
            - |
              /opt/keycloak/bin/kc.sh start-dev --http-enabled=true --hostname-strict=false --hostname-strict-https=false &

              echo "Running init script..."
              sh /opt/keycloak/init/init-keycloak.sh

              wait

          ports:
            - containerPort: 8080
          env:
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL_HOST
              value: "postgres"
            - name: KC_DB_URL_DATABASE
              value: "forms-ai"
            - name: KC_DB_USERNAME
              value: "postgres"
            # TODO: secret, KC_DB_PASSWORD
            - name: KC_DB_PASSWORD
              value: "postgres-secret"
            # !!!TODO: secret
            - name: KEYCLOAK_ADMIN
              value: "keycloak"
            # TODO: secret, KEYCLOAK_ADMIN_PASSWORD
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "keycloak-secret"
            # !!!TODO: secret
            - name: KC_HOSTNAME
              value: "keycloak.team-kruschefan.local"
            - name: KC_PROXY
              value: edge
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KEYCLOAK_FORMSAI_USER
              value: "user-service"
            - name: KEYCLOAK_FORMSAI_PASSWORD
              value: "user-service-secret"
            - name: KEYCLOAK_MOCK_USER
              value: "mock-user"
            - name: KEYCLOAK_MOCK_USER_PASSWORD
              value: "mock-user-secret"
            - name: KEYCLOAK_MOCK_USER_EMAIL
              value: "mock@mock.com"
            - name: KEYCLOAK_MOCK_USER_FIRST_NAME
              value: Mock
            - name: KEYCLOAK_MOCK_USER_LAST_NAME
              value: User
      
      volumes:
        - name: keycloak-init-script
          configMap:
            name: keycloak-init-script
