alertmanager:
  enabled: false

server:
  service:
    type: ClusterIP
    port: 9090
  ingress:
    enabled: false

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheus-node-exporter:
  enabled: true

serviceAccount:
  create: true
  name: ""

# TODO: change ingress config
ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

service:
    type: ClusterIP
    port: 9090

image:
  repository: bitnami/prometheus
  tag: 2.44.0-debian-11-r0
  pullPolicy: IfNotPresent
