spring:
  application:
    name: template-service

  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: ${MONGO_INIT_DB_DATABASE:forms-ai}
      username: ${MONGO_INITDB_ROOT_USERNAME:mongo}
      password: ${MONGO_INITDB_ROOT_PASSWORD:mongo-secret}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9001/realms/forms-ai
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: unrestricted

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

jwt:
  auth:
    converter:
      resource-id: angular-frontend
      principle-attribute: preferred_username
