replicaCount: 1

image:
  repository: ghcr.io/YOUR_USERNAME/user-service # TODO: push image to registry
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8083

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: KEYCLOAK_REALM
    value: FormsAI
