replicaCount: 1

image:
  repository: ghcr.io/cjzbeastmode/user-service:latest
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8083

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: KEYCLOAK_REALM
    value: FormsAI
