replicaCount: 1

image:
  repository: ghcr.io/aet-devops25/user-service # TODO: push image to registry
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP 
  port: 8083

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: KEYCLOAK_REALM
    value: master
  - name: KEYCLOAK_SERVER_URL
    value: http://keycloak:80
  - name: KEYCLOAK_CLIENT_ID
    value: admin-cli
  - name: KEYCLOAK_USERNAME
    value: admin
  - name: KEYCLOAK_PASSWORD
    value: admin
  - name: SPRING_DATA_MONGODB_URI
    value: mongodb://root:password@mongo:27017/admin

serviceAccount:
  create: true
  name: ""

# TODO: change ingress config
ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80