---
- name: Provision EC2 instance
  hosts: all
  become: yes
  vars:
        ansible_user: ec2-user

  tasks:
    - name: Ensure dnf cache is updated
      ansible.builtin.dnf:
        update_cache: yes

    - name: Install base packages
      ansible.builtin.dnf:
        name:
          - jq
          - git
        state: present

    - import_tasks: tasks/install_docker.yml

    - name: Remove existing app directory if it exists
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/app"
        state: absent

    - name: Clone repo
      ansible.builtin.git:
        repo: "https://github.com/AET-DevOps25/team-kruschefan.git"
        dest: "/home/{{ ansible_user }}/app"
        version: main
        force: yes

    - name: Generate .env file for Docker Compose
      ansible.builtin.template:
        src: templates/env.j2
        dest: "/home/{{ ansible_user }}/app/.env.secret"
        mode: "0600"

    - name: Run API setup script
      ansible.builtin.shell: sh api/scripts/setup.sh
      args:
        chdir: /home/ec2-user/app

    # - name: Run Docker Compose
    #   community.docker.docker_compose_v2:
    #     project_src: /home/ec2-user/app
    #     state: present
