# Docker-based routing
spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  data:
    mongodb:
      uri: mongodb://mongo:mongo-secret@mongo:27017/forms-ai

  cloud:
    gateway:
      routes:
        - id: form-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/form/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        - id: template-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/template/**
          filters:
            - StripPrefix=1

        - id: genai-generate
          uri: http://localhost:8000
          predicates:
            - Path=/api/generate_form
          filters:
            - StripPrefix=1

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: unrestricted
  server:
    port: 8080

