# Docker-based routing
spring:
  application:
    name: api-gateway
  
  main:
    web-application-type: reactive

  data:
    mongodb:
      uri: mongodb://mongo:mongo-secret@mongo:27017/forms-ai

  cloud:
    gateway:
      routes:
        - id: form-service
          uri: http://form-service:8081
          predicates:
          - Path=/**
          - Path=/form/**

        - id: user-service
          uri: http://user-service:8083
          predicates:
          - Path=/**
          - Path=/user/**

        - id: template-service
          uri: http://template-service:8082
          predicates:
          - Path=/**
          - Path=/template/**

        - id: genai-generate
          uri: http://langchain-app:8000
          predicates:
          - Path=/**

# server:
#   port: 8080

# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info,prometheus
#   endpoint:
#     prometheus:
#       access: unrestricted
#   server:
#     port: 8080

