replicaCount: 1

image:
  repository: ghcr.io/aet-devops25/api-gateway-service # TODO: push image to registry
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker

serviceAccount:
  create: true
  name: ""

# TODO: change ingress
ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80