replicaCount: 1

image:
  repository: ghcr.io/YOUR_USERNAME/api-gateway # TODO: push image to registry
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
