replicaCount: 1

image:
  repository: ghcr.io/cjzbeastmode/api-gateway:latest
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
