replicaCount: 1

image:
  repository: ghcr.io/cjzbeastmode/client
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: ""

# TODO: change ingress
ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

imagePullSecrets:
  - name: ghcr-cred
