replicaCount: 1

image:
  repository: ghcr.io/cjzbeastmode/genai
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

env:
  - name: PYTHONUNBUFFERED
    value: "1"
  - name: MONGO_URI
    valueFromSecret:
      name: project-secrets
      key: mongo_uri
  - name: HUGGINGFACE_API_KEY
    value: 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

serviceAccount:
  create: true
  name: ""

# TODO: change ingress config
ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

imagePullSecrets:
  - name: ghcr-cred
