replicaCount: 1

image:
  repository: metabase/metabase
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  - name: MB_DB_FILE
    value: /metabase-data/metabase.db

volumeMounts:
  - name: metabase-data
    mountPath: /metabase-data

volumes:
  - name: metabase-data
    persistentVolumeClaim:
      claimName: metabase-pvc
