repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: postgres
    namespace: default
    chart: bitnami/postgresql
    values:
      - ./postgres/values.yaml

  - name: keycloak
    namespace: default
    chart: ./keycloak

  - name: user-service
    namespace: default
    chart: ./user-service

  - name: form-service
    namespace: default
    chart: ./form-service

  - name: template-service
    namespace: default
    chart: ./template-service

  - name: api-gateway
    namespace: default
    chart: ./api-gateway

  - name: mongodb
    namespace: default
    chart: ./mongodb

  - name: langchain-app
    namespace: default
    chart: ./langchain-app

  - name: mongo-express
    namespace: default
    chart: ./mongo-express

  - name: mongo-schema-loader
    namespace: default
    chart: ./mongo-schema-loader

  - name: client
    namespace: default
    chart: ./client

  - name: metabase
    namespace: default
    chart: ./metabase

  - name: weaviate
    namespace: default
    chart: ./weaviate

  - name: prometheus
    namespace: default
    chart: ./prometheus

  - name: grafana
    namespace: default
    chart: ./grafana

  - name: alertmanager
    namespace: default
    chart: ./alertmanager
