repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: keycloak
    namespace: team-kruschefan
    chart: ./keycloak

  - name: user-service
    namespace: team-kruschefan
    chart: ./user-service

  - name: form-service
    namespace: team-kruschefan
    chart: ./form-service

  - name: template-service
    namespace: team-kruschefan
    chart: ./template-service

  - name: api-gateway
    namespace: team-kruschefan
    chart: ./api-gateway

  - name: langchain-app
    namespace: team-kruschefan
    chart: ./langchain-app

  - name: client
    namespace: team-kruschefan
    chart: ./client

  - name: prometheus
    namespace: team-kruschefan
    chart: ./prometheus

  - name: grafana
    namespace: team-kruschefan
    chart: ./grafana

  - name: alertmanager
    namespace: team-kruschefan
    chart: ./alertmanager

  - name: postgres
    namespace: team-kruschefan
    chart: ./postgres
