replicaCount: 1

image:
  repository: ghcr.io/cjzbeastmode/genai:latest
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  - name: PYTHONUNBUFFERED
    value: "1"
  - name: MONGO_URI
    valueFromSecret:
      name: project-secrets
      key: mongo_uri
  - name: HUGGINGFACEHUB_API_TOKEN
    valueFromSecret:
      name: project-secrets
      key: huggingface_api_key
