replicaCount: 1

image:
  repository: ghcr.io/aet-devops25/genai # TODO: push image to registry
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  - name: PYTHONUNBUFFERED
    value: "1"
  - name: MONGO_URI
    valueFromSecret:
      name: project-secrets
      key: mongo_uri
  - name: HUGGINGFACEHUB_API_TOKEN
    valueFromSecret:
      name: project-secrets
      key: huggingface_api_key

serviceAccount:
  create: true
  name: ""

# TODO: change ingress config
ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80