config:
  global:
    resolve_timeout: 5m

  route:
    group_by:
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
    receiver: default

  receivers:
    - name: default
      email_configs:
        - to: your-email@example.com
          from: alertmanager@example.com
          smarthost: smtp.example.com:587
          auth_username: alertmanager@example.com
          auth_identity: alertmanager@example.com
          auth_password: YOUR_EMAIL_PASSWORD

service:
  type: ClusterIP
  port: 9093

serviceAccount:
  create: true
  name: ""

# TODO: change ingress
ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

image:
  repository: prom/alertmanager
  tag: v0.25.0
  pullPolicy: IfNotPresent
