replicaCount: 1

image:
  repository: ghcr.io/cjzbeastmode/genai
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

env:
  - name: PYTHONUNBUFFERED
    value: "1"
  - name: OPENUI_API_KEY
    valueFrom:
      secretKeyRef:
        name: project-secrets
        key: OPENUI_API_KEY

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

imagePullSecrets:
  - name: ghcr-cred
