{
 "title": "Microservices Surveillance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "User Request Duration (Sum)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "user_request_processing_duration_seconds_sum"
    }
   ]
  },
  {
   "title": "User Request Duration (Count)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "user_request_processing_duration_seconds_count"
    }
   ]
  },
  {
   "title": "Form Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "form_get_all_requests_total" }
   ]
  },
  {
   "title": "Form Requests Success",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "form_get_all_requests_success_total"
    }
   ]
  },
  {
   "title": "Template Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "template_get_all_requests_total"
    }
   ]
  },
  {
   "title": "Template Requests Success",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "template_get_all_requests_success_total"
    }
   ]
  }
 ]
}