{
 "title": "Spring Security Auth Flows Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Authentication Duration (Sum)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "spring_security_authentications_seconds_sum"
    }
   ]
  },
  {
   "title": "Authentication Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "spring_security_authentications_seconds_count"
    }
   ]
  },
  {
   "title": "Authorization Duration (Sum)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "spring_security_authorizations_seconds_sum"
    }
   ]
  },
  {
   "title": "Authorization Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "spring_security_authorizations_seconds_count"
    }
   ]
  },
  {
   "title": "Active Authentications",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "spring_security_authentications_active_seconds_count"
    }
   ]
  },
  {
   "title": "Active Authorizations",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "spring_security_authorizations_active_seconds_count"
    }
   ]
  }
 ]
}