name: Deploy to Kubernetes via Helmfile

on:
  push:
    branches:
      - main
      - feat/testing
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      KEYCLOAK_USER: ${{ secrets.KEYCLOAK_USER }}
      KEYCLOAK_PASSWORD: ${{ secrets.KEYCLOAK_PASSWORD }}
      KEYCLOAK_ADMIN: ${{ secrets.KEYCLOAK_ADMIN }}
      KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
      KEYCLOAK_FORMSAI_USER: ${{ secrets.KEYCLOAK_FORMSAI_USER }}
      KEYCLOAK_FORMSAI_PASSWORD: ${{ secrets.KEYCLOAK_FORMSAI_PASSWORD }}
      KEYCLOAK_MOCK_USER: ${{ secrets.KEYCLOAK_MOCK_USER }}
      KEYCLOAK_MOCK_USER_PASSWORD: ${{ secrets.KEYCLOAK_MOCK_USER_PASSWORD }}
      KEYCLOAK_MOCK_USER_EMAIL: ${{ secrets.KEYCLOAK_MOCK_USER_EMAIL }}
      KEYCLOAK_MOCK_USER_FIRST_NAME: ${{ secrets.KEYCLOAK_MOCK_USER_FIRST_NAME }}
      KEYCLOAK_MOCK_USER_LAST_NAME: ${{ secrets.KEYCLOAK_MOCK_USER_LAST_NAME }}
      KC_DB_USERNAME: ${{ secrets.KC_DB_USERNAME }}
      KC_DB_PASSWORD: ${{ secrets.KC_DB_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_URI: ${{ secrets.POSTGRES_URI }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      MONGO_INITDB_DATABASE: ${{ secrets.MONGO_INITDB_DATABASE }}
      MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      OPENUI_API_KEY: ${{ secrets.OPENUI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_EMAIL: ${{ secrets.GHCR_EMAIL }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up OpenAPI config files
        run: |
          echo "Setting up OpenAPI config files..."
          sh api/scripts/setup.sh

      # Test Java services
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Run services tests
        run: |
          cd services/user-service
          mvn clean test
          cd ../..

          cd services/template-service
          mvn clean test
          cd ../..

          cd services/form-service
          mvn clean test
          cd ../..

          cd services/api-gateway-service
          mvn clean test
          cd ../..

      # Test Python GenAI service
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install GenAI dependencies
        run: pip install -r services/GenAI/requirements.txt

      - name: Run GenAI tests
        run: pytest services/GenAI/test.py

      # Test Angular web-client
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install client ependencies
        run: |
          cd web-client
          npm install
          cd ..

      - name: Run client tests
        run: |
          cd web-client
          npm test
          cd ..

      # Set up Kubernetes
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "latest"

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker images
        run: |
          # api-gateway
          echo "Building and pushing api-gateway image..."
          cd services/api-gateway-service
          docker buildx build --platform linux/amd64 -t ghcr.io/cjzbeastmode/api-gateway:latest -f Dockerfile . && docker push ghcr.io/cjzbeastmode/api-gateway:latest
          cd ../..

          # client
          echo "Building and pushing web-client image..."
          cd web-client
          docker buildx build --platform linux/amd64 -t ghcr.io/cjzbeastmode/client:latest -f Dockerfile . && docker push ghcr.io/cjzbeastmode/client:latest
          cd ..

          # form-service
          echo "Building and pushing form-service image..."
          cd services/form-service
          docker buildx build --platform linux/amd64 -t ghcr.io/cjzbeastmode/form-service:latest -f Dockerfile . && docker push ghcr.io/cjzbeastmode/form-service:latest
          cd ../..

          # GenAI
          echo "Building and pushing GenAI images..."
          cd services/GenAI
          docker buildx build --platform linux/amd64 -t ghcr.io/cjzbeastmode/genai:latest -f Dockerfile . && docker push ghcr.io/cjzbeastmode/genai:latest
          cd ../..

          # template-service
          echo "Building and pushing template-service image..."
          cd services/GenAI
          docker buildx build --platform linux/amd64 -t ghcr.io/cjzbeastmode/template-service:latest -f Dockerfile . && docker push ghcr.io/cjzbeastmode/template-service:latest
          cd ../..

          # user-service
          echo "Building and pushing user-service image..."
          cd services/user-service
          docker buildx build --platform linux/amd64 -t ghcr.io/cjzbeastmode/user-service:latest -f Dockerfile . && docker push ghcr.io/cjzbeastmode/user-service:latest
          cd ../..

      - name: Create multiple Kubernetes secrets
        run: |
          kubectl delete secret project-secrets --namespace team-kruschefan-project --ignore-not-found
          kubectl create secret generic project-secrets \
            --namespace team-kruschefan-project \
            --from-literal=GITHUB_TOKEN="$GITHUB_TOKEN" \
            --from-literal=OPENUI_API_KEY="$OPENUI_API_KEY" \

          kubectl delete secret postgresql-secrets --namespace team-kruschefan-project --ignore-not-found
          kubectl create secret generic postgresql-secrets \
            --namespace team-kruschefan-project \
            --from-literal=POSTGRES_USER="$POSTGRES_USER" \
            --from-literal=POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
            --from-literal=POSTGRES_URI="$POSTGRES_URI" \
            --from-literal=POSTGRES_DB=forms-ai

          kubectl delete secret keycloak-secret --namespace team-kruschefan-project --ignore-not-found
          kubectl create secret generic keycloak-secret \
            --namespace team-kruschefan-project \
            --from-literal=KEYCLOAK_USER="$KEYCLOAK_USER" \
            --from-literal=KEYCLOAK_PASSWORD="$KEYCLOAK_PASSWORD" \
            --from-literal=KEYCLOAK_ADMIN="$KEYCLOAK_ADMIN" \
            --from-literal=KEYCLOAK_ADMIN_PASSWORD="$KEYCLOAK_ADMIN_PASSWORD" \
            --from-literal=KEYCLOAK_FORMSAI_USER="$KEYCLOAK_FORMSAI_USER" \
            --from-literal=KEYCLOAK_FORMSAI_PASSWORD="$KEYCLOAK_FORMSAI_PASSWORD" \
            --from-literal=KC_DB_USERNAME="$KC_DB_USERNAME" \
            --from-literal=KC_DB_PASSWORD="$KC_DB_PASSWORD" \

          kubectl delete secret mongo-secret --namespace team-kruschefan-project --ignore-not-found
          kubectl create secret generic mongo-secret \
            --namespace team-kruschefan-project \
            --from-literal=MONGO_INITDB_ROOT_USERNAME="$MONGO_INITDB_ROOT_USERNAME" \
            --from-literal=MONGO_INITDB_ROOT_PASSWORD="$MONGO_INITDB_ROOT_PASSWORD" \
            --from-literal=MONGO_INITDB_DATABASE="$MONGO_INITDB_DATABASE" \
            --from-literal=MONGO_USERNAME="$MONGO_USERNAME" \
            --from-literal=MONGO_PASSWORD="$MONGO_PASSWORD" \
            --from-literal=MONGO_DATABASE="$MONGO_DATABASE" \
            --from-literal=MONGO_URI="$MONGO_URI"

          kubectl delete secret ghcr-cred --namespace team-kruschefan-project --ignore-not-found
          kubectl create secret docker-registry ghcr-cred \
            --namespace team-kruschefan-project \
            --docker-server=ghcr.io \
            --docker-username="$GHCR_USERNAME" \
            --docker-password="$GITHUB_TOKEN" \
            --docker-email="$GHCR_EMAIL" \

      - name: Deploy with Helmfile
        uses: helmfile/helmfile-action@v2.0.4
        with:
          helmfile-version: "v0.150.0"
          helm-version: "v3.11.0"
          helmfile-args: apply --namespace team-kruschefan-project
          helmfile-workdirectory: infra/helm

      - name: Apply Ingress resource
        run: kubectl apply -f infra/helm/ingress.yaml --namespace team-kruschefan-project
