name: Deploy to Kubernetes via Helmfile

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      KEYCLOAK_USER: ${{ secrets.KEYCLOAK_USER }}
      KEYCLOAK_PASSWORD: ${{ secrets.KEYCLOAK_PASSWORD }}
      KEYCLOAK_ADMIN_USER: ${{ secrets.KEYCLOAK_ADMIN_USER }}
      KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
      KEYCLOAK_FORMSAI_USER: ${{ secrets.KEYCLOAK_FORMSAI_USER }}
      KEYCLOAK_FORMSAI_PASSWORD: ${{ secrets.KEYCLOAK_FORMSAI_PASSWORD }}
      KC_DB_USERNAME: ${{ secrets.KC_DB_USERNAME }}
      KC_DB_PASSWORD: ${{ secrets.KC_DB_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_URI: ${{ secrets.POSTGRES_URI }}
      HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_EMAIL: ${{ secrets.GHCR_EMAIL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Set up Helmfile
        run: |
          curl -L https://github.com/helmfile/helmfile/releases/latest/download/helmfile_linux_amd64 -o helmfile
          chmod +x helmfile
          sudo mv helmfile /usr/local/bin/

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker images
        run: |
          # api-gateway
          docker buildx build --platform linux/amd64 -t ghcr.io/cjzbeastmode/api-gateway:latest -f api-gateway-service/Dockerfile . && docker push ghcr.io/cjzbeastmode/api-gateway:latest

          # client
          cd client
          docker buildx build --platform linux/amd64 -t ghcr.io/cjzbeastmode/client:latest -f Dockerfile . && docker push ghcr.io/cjzbeastmode/client:latest
          cd ..

          # form-service
          docker buildx build --platform linux/amd64 -t ghcr.io/cjzbeastmode/form-service:latest -f form-service/Dockerfile . && docker push ghcr.io/cjzbeastmode/form-service:latest

          # GenAI
          cd GenAI
          docker buildx build --platform linux/amd64 -t ghcr.io/cjzbeastmode/genai:latest -f Dockerfile . && docker push ghcr.io/cjzbeastmode/genai:latest
          cd ..

          # template-service
          docker buildx build --platform linux/amd64 -t ghcr.io/cjzbeastmode/template-service:latest -f template-service/Dockerfile . && docker push ghcr.io/cjzbeastmode/template-service:latest

          # user-service
          docker buildx build --platform linux/amd64 -t ghcr.io/cjzbeastmode/user-service:latest -f user-service/Dockerfile . && docker push ghcr.io/cjzbeastmode/user-service:latest

      - name: Create multiple Kubernetes secrets
        run: |
          kubectl create secret generic project-secrets \
            --from-literal=GITHUB_TOKEN="$GITHUB_TOKEN" \
            --from-literal=HUGGINGFACE_API_KEY="$HUGGINGFACE_API_KEY" \
            --dry-run=client -o yaml | kubectl apply -f -

          kubectl create secret generic postgresql-secrets \
            --from-literal=POSTGRES_USER="$POSTGRES_USER" \
            --from-literal=POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
            --from-literal=POSTGRES_URI="$POSTGRES_URI" \
            --from-literal=POSTGRES_DB=forms-ai \
            --dry-run=client -o yaml | kubectl apply -f -

          kubectl create secret generic keycloak-secret \
            --from-literal=username="$KEYCLOAK_USER" \
            --from-literal=password="$KEYCLOAK_PASSWORD" \
            --from-literal=adminUsername="$KEYCLOAK_ADMIN_USER" \
            --from-literal=adminPassword="$KEYCLOAK_ADMIN_PASSWORD" \
            --from-literal=formsaiUsername="$KEYCLOAK_FORMSAI_USER" \
            --from-literal=formsaiPassword="$KEYCLOAK_FORMSAI_PASSWORD" \
            --from-literal=KC_DB_USERNAME="$KC_DB_USERNAME" \
            --from-literal=KC_DB_PASSWORD="$KC_DB_PASSWORD" \
            --dry-run=client -o yaml | kubectl apply -f -

          kubectl create secret docker-registry ghcr-cred \
            --docker-server=ghcr.io \
            --docker-username="$GHCR_USERNAME" \
            --docker-password="$GITHUB_TOKEN" \
            --docker-email="$GHCR_EMAIL" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy with Helmfile
        run: helmfile apply

      - name: Apply Ingress resource
        run: kubectl apply -f infrastructure/helm/ingress.yaml
