name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_key_name: ${{ secrets.AWS_KEY_NAME }}
      TF_VAR_private_key_path: ~/.ssh/id_rsa

      # App-specific secrets
      HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      KC_DB_USERNAME: ${{ secrets.KC_DB_USERNAME }}
      KC_DB_PASSWORD: ${{ secrets.KC_DB_PASSWORD }}
      KEYCLOAK_ADMIN: ${{ secrets.KEYCLOAK_ADMIN }}
      KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: ./terraform/terraform
        run: terraform init

      - name: Apply Terraform (Provision EC2)
        working-directory: ./terraform/terraform
        run: terraform apply -auto-approve

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Wait for EC2 to be reachable
        run: sleep 60 

      - name: Set up Python for Ansible
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        working-directory: ./ansible/ansible
        run: |
          ansible-playbook -i "ec2-user@$(terraform output -raw public_ip)" playbook.yml --private-key ~/.ssh/id_rsa
      